name: Daily Attendance Bot

on:
  schedule:
    - cron: '0 4,15 * * *'
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          GREYTHR_ID: ${{ secrets.GREYTHR_ID }}
          GREYTHR_PASSWORD: ${{ secrets.GREYTHR_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SHEETY_URL: ${{ secrets.SHEETY_URL }}
          ORG_CC: ${{ secrets.ORG_CC }}
          MANAGER_EMAIL: ${{ secrets.MANGER_EMAIL }}
          GREYTHR_URL: ${{ secrets.GREYTHR_URL }}
        run: python main.py
